Lecture 3/hw
virter/react-20240513 pull request #4
Opened 2024-05-26 15:45 UTC by virter

2024-05-26 15:49 UTC, virter commented
При запуске приложения выкидывает warning-и в консоли браузера если не указывать key пропы:
Warning: Each child in a list should have a unique "key" prop.
Их можно отключить?

Осталась проблема с предыдущей домашки, count сохраняется с привязкой к определенному li в списке, но обычно значение должно привязываться к определенному элементу определённого таба

2024-05-27 14:45 UTC, SArchieEdu commented
> При запуске приложения выкидывает warning-и в консоли браузера если не указывать key пропы: Warning: Each child in a list should have a unique "key" prop. Их можно отключить?
> 
> Осталась проблема с предыдущей домашки, count сохраняется с привязкой к определенному li в списке, но обычно значение должно привязываться к определенному элементу определённого таба

пока не обращайте внимание на эти проблемы, позже мы их уберем

2024-05-27 14:47 UTC, SArchieEdu requested changes

2024-05-27 14:47 UTC, SArchieEdu commented on src/components/dish/component.jsx
> +};
этот хук не похож на тот, который мы делали на лекции
необходимо сделать как на лекции, чтобы попробовать использовать новые хуки

2024-05-28 11:55 UTC, merged